services:
    db:
        image: postgres:13
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_NAME}
        volumes:
            - ./db:/var/lib/postgresql/data
        networks:
            - default

    app:
        env_file:
            - .env
        build:
            context: .
            args:
                NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
                CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
                DB_URL: ${DB_URL}
        ports:
            - ${APP_PORT}:3000
        restart: always
        depends_on:
            - db
        environment:
            DB_URL: ${DB_URL}
        networks:
            - default

networks:
    default:
        external: true
        name: ${NETWORK_NAME}
